// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE0i5R4HSbjFmKgNNrklZeM2oOrVXo1Tg',
    appId: '1:703302883700:android:c2568ea4c9e12e34e17421',
    messagingSenderId: '703302883700',
    projectId: 'hung-multiple-app',
    storageBucket: 'hung-multiple-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB5cmzIpIF0_SSGopJTps9Geohh-tfa4Q',
    appId: '1:703302883700:ios:67f3adc3eb1ee03ce17421',
    messagingSenderId: '703302883700',
    projectId: 'hung-multiple-app',
    storageBucket: 'hung-multiple-app.firebasestorage.app',
    iosBundleId: 'com.example.hungMultipleApp',
  );
}
